### PR TITLE
Update resource 2

### PR DESCRIPTION
**Pull request by FuqiX**
@theisuru Hi, Isuru. do you mind having a look at this one.

In the decision tree, one node is 
```
{
        "text": "Data validation",
        "description": "",
        "labels": [
          "validation","data validation","constraint validation", "schema", "schema structure"
        ],
        "next": "0"
      }
``` 
I am expecting to find all resources with those five labels. And resource "tool: Elixir biovalidator"  has lable "schema". but it's not returned in the wizard outcome.

The path is http://localhost:8080/wizard?answers=Biologist&answers=I%20have%20data%20to%20be%20generated&answers=Interoperability&answers=Data%20validation

### CODE REVIEW

**Comment by FuqiX** [comment]
@theisuru Do you mind having a look at this one ? thanks!

**Comment by theisuru** [comment]
Looks like there are some errors in resources. This path gives me an error. 
image

**Comment by FuqiX** [comment]
That's also what makes me confused.

Are the labels of the nodes used?

For example, Node "Data deposition" has label "data deposition", and there are 8 resources with the label "data deposition"/ They should be found.

I also found other node labels are not used.

**Comment by theisuru** [comment]
No data is shown becasue of errors in resources file.
For example in this instance, hasParent is developed as an array, but resource it is listed as an single element. 
Therefore, when we are adding new elements its alsway good to compare it with an existing ones.

```fw:hasParent    ( <fw:process-data-access-and-ethics> ) ;```

**Pull request closed without merging**
